language: python

python:
  - '3.6'

addons:
  apt:
    packages:
    - tesseract-ocr

install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

script:
  - flake8 salvius
  - sphinx-build -b html ./docs_source/ ./docs/
  - nosetests --with-coverage --cover-package=salvius

after_success:
  - coveralls
